// <auto-generated />
using System;
using System.Collections.Generic;
using CardgameDungeon.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardgameDungeon.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CardgameDungeonDbContext))]
    partial class CardgameDungeonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.3.25171.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CardSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.HasIndex("CardType");

                    b.HasIndex("Rarity");

                    b.ToTable("Cards", (string)null);

                    b.HasDiscriminator<string>("CardType").HasValue("Card");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.CardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CardSets", (string)null);
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.MarketplaceListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OwnedCardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("SellerId");

                    b.ToTable("MarketplaceListings", (string)null);
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.OwnedCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReserved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("OwnedCards", (string)null);
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.PlayerRating", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Elo")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.HasIndex("Elo");

                    b.ToTable("PlayerRatings", (string)null);
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.PlayerWallet", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<int>("DailyRewardsClaimedToday")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("LastDailyRewardDate")
                        .HasColumnType("date");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerWallets", (string)null);
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.QueueEntry", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<int>("Elo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PlayerId");

                    b.HasIndex("QueueType");

                    b.ToTable("QueueEntries", (string)null);
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<int>("EntryFee")
                        .HasColumnType("integer");

                    b.Property<int>("PrizePool")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Tournaments", (string)null);
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.TournamentParticipant", b =>
                {
                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EliminatedInRound")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEliminated")
                        .HasColumnType("boolean");

                    b.HasKey("TournamentId", "PlayerId");

                    b.ToTable("TournamentParticipants", (string)null);
                });

            modelBuilder.Entity("CardgameDungeon.Infrastructure.Data.Persistence.DeckListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("AdventurerCardIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("BossCardId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("DungeonRoomCardIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<Guid>>("EnemyCardIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("DeckLists", (string)null);
                });

            modelBuilder.Entity("CardgameDungeon.Infrastructure.Data.Persistence.MatchStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("MatchStates", (string)null);
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.AllyCard", b =>
                {
                    b.HasBaseType("CardgameDungeon.Domain.Entities.Card");

                    b.Property<string>("Effect")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Effect");

                    b.Property<int>("HitPoints")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("HitPoints");

                    b.Property<int>("Initiative")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Initiative");

                    b.Property<bool>("IsAmbusher")
                        .HasColumnType("boolean");

                    b.Property<int>("Strength")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Strength");

                    b.Property<int>("Treasure")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Treasure");

                    b.HasDiscriminator().HasValue("Ally");
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.BossCard", b =>
                {
                    b.HasBaseType("CardgameDungeon.Domain.Entities.Card");

                    b.Property<string>("Effect")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Effect");

                    b.Property<int>("HitPoints")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("HitPoints");

                    b.Property<int>("Initiative")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Initiative");

                    b.Property<int>("Strength")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Strength");

                    b.HasDiscriminator().HasValue("Boss");
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.DungeonRoomCard", b =>
                {
                    b.HasBaseType("CardgameDungeon.Domain.Entities.Card");

                    b.Property<string>("Effect")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Effect");

                    b.Property<int>("MonsterCostBudget")
                        .HasColumnType("integer");

                    b.Property<IReadOnlyList<Guid>>("MonsterIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("MonsterIds");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<IReadOnlyList<Guid>>("TrapIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("TrapIds");

                    b.HasDiscriminator().HasValue("DungeonRoom");
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.EquipmentCard", b =>
                {
                    b.HasBaseType("CardgameDungeon.Domain.Entities.Card");

                    b.Property<int>("HitPointsModifier")
                        .HasColumnType("integer");

                    b.Property<int>("InitiativeModifier")
                        .HasColumnType("integer");

                    b.Property<int>("StrengthModifier")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Equipment");
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.MonsterCard", b =>
                {
                    b.HasBaseType("CardgameDungeon.Domain.Entities.Card");

                    b.Property<string>("Effect")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Effect");

                    b.Property<int>("HitPoints")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("HitPoints");

                    b.Property<int>("Initiative")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Initiative");

                    b.Property<int>("Strength")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Strength");

                    b.Property<int>("Treasure")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Treasure");

                    b.HasDiscriminator().HasValue("Monster");
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.TrapCard", b =>
                {
                    b.HasBaseType("CardgameDungeon.Domain.Entities.Card");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Effect");

                    b.HasDiscriminator().HasValue("Trap");
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.Card", b =>
                {
                    b.HasOne("CardgameDungeon.Domain.Entities.CardSet", null)
                        .WithMany("Cards")
                        .HasForeignKey("CardSetId");
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.TournamentParticipant", b =>
                {
                    b.HasOne("CardgameDungeon.Domain.Entities.Tournament", null)
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.CardSet", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("CardgameDungeon.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
